[package]
name = "veracity-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
num-traits = "0.2.19"
veracity-data = { path = "../veracity-data" }
veracity-types = { path = "../veracity-types" }
